apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  namespace: default
  labels:
    app: jenkins-demo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
  selector:
    app: jenkins-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  labels:
    app: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: k8s-demo
        image: firexuxiaoman/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>